checkout/urls.py
from django.urls import path

from .views import CheckoutView


app_name = "checkout"


urlpatterns = [
    path("checkout/", CheckoutView.as_view(), name="checkout"),
]

core/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import HomeView, ItemDetailView

app_name = "core"


urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("product/<slug>/", ItemDetailView.as_view(), name="product"),
    path(
        "data-protection/",
        TemplateView.as_view(template_name="data_protection.html"),
        name="data-protection",
    ),
    path(
        "impressum/",
        TemplateView.as_view(template_name="impressum.html"),
        name="impressum",
    ),
    path("api-doc/", TemplateView.as_view(template_name="api.html"), name="api-doc"),
]

eshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

urlpatterns = [
    path("api/v1/", include("rest_framework.urls", namespace="rest_framework")),
    path("api/v1/", include("core.api_core.urls")),
    path("i18n/", include("django.conf.urls.i18n")),  # For set_language in Navbar
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path("__debug__", include(debug_toolbar.urls))]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()
urlpatterns += i18n_patterns(
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("core.urls", namespace="core")),
    path("", include("order.urls", namespace="order")),
    path("", include("checkout.urls", namespace="checkout")),
    path("payment/", include("payment.urls", namespace="payment")),
)

order/urls.py
from django.urls import path

from .cart import add_to_cart, remove_from_cart, remove_single_item_from_cart
from .views import OrdersFinishedView, OrderView


app_name = "order"


urlpatterns = [
    path("cart/", OrderView.as_view(), name="cart-summary"),
    path("cart/add/<slug>/", add_to_cart, name="add-to-cart"),
    path("cart/remove/<slug>/", remove_from_cart, name="remove-from-cart"),
    path(
        "cart/remove-single-item-from-cart/<slug>/",
        remove_single_item_from_cart,
        name="remove-single-item-from-cart",
    ),
    path("orders/", OrdersFinishedView.as_view(), name="orders-finished"),
]

payment/urls.py
from django.urls import path

from .views import PaypalView, capture, getClientId

app_name = "payment"

urlpatterns = [
    path("", PaypalView.as_view(), name="payment"),
    path("capture/<order_id>/", capture, name="paypal-capture"),
    path("client-id/", getClientId, name="client-id"),
]

refund/urls.py
from django.urls import path

from .views import RequestRefundView


app_name = "refund"


urlpatterns = [
    path("request-refund/", RequestRefundView.as_view(), name="request-refund"),
]

checkout/models.py
from django.db import models
from django.conf import settings
from django.utils.translation import gettext as _

from django_countries import Countries
from django_countries.fields import CountryField


class EUCountries(Countries):
    """Defining only countries to be available in checkout form"""

    only = [
        "BE",
        "BG",
        "CZ",
        "DK",
        "DE",
        "EE",
        "IE",
        "GR",
        "ES",
        "FR",
        "HR",
        "IT",
        "CY",
        "LV",
        "LT",
        "LU",
        "HU",
        "MT",
        "NL",
        "AT",
        "PL",
        "PT",
        "RO",
        "SI",
        "SK",
        "FI",
        "SE",
        "NO",
        "LI",
        "CH",
        "GB",
    ]


class Address(models.Model):
    """Address for order placement"""

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        default=None,
    )
    email = models.EmailField()
    shipping_name = models.CharField(
        max_length=120, verbose_name=_("Shipping full name")
    )
    shipping_street_address = models.CharField(
        max_length=100, verbose_name=_("Shipping street address")
    )
    shipping_apartment_address = models.CharField(
        max_length=100, verbose_name=_("Shipping apartment address"), blank=True
    )
    shipping_city = models.CharField(max_length=100, verbose_name=_("Shipping city"))
    shipping_country = CountryField(
        multiple=False, countries=EUCountries, verbose_name=_("Shipping country")
    )
    shipping_zip = models.CharField(max_length=10)
    billing_name = models.CharField(max_length=120, verbose_name=_("Billing full name"))
    billing_street_address = models.CharField(
        max_length=100, verbose_name=_("Billing street address")
    )
    billing_apartment_address = models.CharField(
        max_length=100, verbose_name=_("Billing apartment address"), blank=True
    )
    billing_city = models.CharField(max_length=100, verbose_name=_("Billing city"))
    billing_country = CountryField(
        multiple=False, countries=EUCountries, verbose_name=_("Billing country")
    )
    billing_zip = models.CharField(max_length=10)
    default = models.BooleanField(
        default=False, verbose_name=_("Save for future usage"), blank=True
    )  # If True, address will be offered to user in future checkouts as initials

    def __str__(self):
        return str(self.shipping_country)

    class Meta:
        verbose_name_plural = _("Addresses")

core/models.py
"""Core models: Item, CategoryItem, Carousel"""

from functools import cached_property
from autoslug import AutoSlugField
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext as _
from embed_video.fields import EmbedVideoField

from common.models import carousel_image_path, compress, item_image_path


LABEL_CHOICES = (
    ("n", "NEW"),
    ("h", "HOT"),
)


class CategoryItem(models.Model):
    """Category for items"""

    name = models.CharField(max_length=20)
    slug = AutoSlugField(populate_from="name", unique_with="id")

    def __str__(self):
        return str(self.name)

    class Meta:
        verbose_name = _("Item category")
        verbose_name_plural = _("Item categories")


class Item(models.Model):
    """Item model for creating new items for purchase"""

    title = models.CharField(max_length=100, verbose_name=_("Title"))
    slug = AutoSlugField(populate_from="title", unique_with="id")
    price = models.DecimalField(
        decimal_places=2, max_digits=10, verbose_name=_("Price")
    )
    delivery_price = models.DecimalField(
        decimal_places=2,
        max_digits=10,
        blank=True,
        verbose_name=_("Delivery price"),
        default=0,
    )
    discount = models.DecimalField(
        decimal_places=2,
        max_digits=10,
        blank=True,
        verbose_name=_("Discount"),
        default=0,
    )
    category = models.ForeignKey(
        "CategoryItem",
        on_delete=models.SET_NULL,
        null=True,
        verbose_name=_("Category"),
    )
    label = models.CharField(choices=LABEL_CHOICES, max_length=1, null=True, blank=True)
    stock = models.PositiveIntegerField(default="1", verbose_name=_("Stock"))
    title_image = models.ImageField(
        upload_to=item_image_path, verbose_name=_("Title image")
    )
    item_video = EmbedVideoField(verbose_name="Item video", blank=True)
    description = models.TextField(verbose_name=_("Description"))
    additional_information = models.TextField(
        blank=True, null=True, verbose_name=_("Additional information")
    )
    created_date = models.DateTimeField(
        auto_now_add=True, verbose_name=_("Creation date")
    )
    ordered_counter = models.PositiveIntegerField(
        default="0", verbose_name=_("Ordered counter")
    )

    class Meta:
        verbose_name = _("Item")
        verbose_name_plural = _("Items")

    def __str__(self):
        return str(self.title)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._old_title_image = self.title_image

    def save(self, *args, **kwargs):
        """
        Checking if the image has been changed. If changed, apply compression and converse to webp
        """
        if self._old_title_image != self.title_image:
            self.title_image = compress(self.title_image)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        """Absolute URL to item"""
        return reverse("core:product", kwargs={"slug": self.slug})

    def get_add_to_cart_url(self):
        """URL to add item to cart i.e. create new Order Item"""
        return reverse("order:add-to-cart", kwargs={"slug": self.slug})

    def get_remove_from_cart_url(self):
        """URL to remove Order Item from cart"""
        return reverse("order:remove-from-cart", kwargs={"slug": self.slug})

    @cached_property
    def get_price_no_discount(self):
        """Price + delivery without discount"""
        return self.price + self.delivery_price

    @cached_property
    def get_final_price(self):
        """Final price - including delivery and discount"""
        return self.price + self.delivery_price - self.discount

    @cached_property
    def get_price_no_delivery(self):
        """Price + discount without delivery"""
        return self.price - self.discount


class ItemImage(models.Model):
    """Images of item"""

    item = models.ForeignKey(
        Item,
        related_name="images",
        on_delete=models.CASCADE,
    )
    image = models.ImageField(upload_to=item_image_path, verbose_name=_("Image"))

    @property
    def slug(self):
        """Getting slug of Item for usage in file upload path"""
        return self.item.slug  # pylint: disable=E1101

    class Meta:
        verbose_name = _("Item image")
        verbose_name_plural = _("Item images")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._old_image = self.image

    def save(self, *args, **kwargs):
        """
        Checking if the image has been changed. If changed, apply compression and converse to webp
        """
        if self._old_image != self.image:
            self.image = compress(self.image)
        super().save(*args, **kwargs)


class Carousel(models.Model):
    """Carousel on home page"""

    img = models.ImageField(upload_to=carousel_image_path)
    title = models.CharField(max_length=120, verbose_name=_("Title"))
    body = models.TextField(verbose_name=_("Body text"))
    alt = models.TextField(verbose_name=_("Alt text"))
    index = models.IntegerField(unique=True)

    class Meta:  # pylint: disable=missing-class-docstring
        verbose_name = _("Carousel")
        verbose_name_plural = _("Carousels")

    def __str__(self):
        return str(self.title)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._old_img = self.img

    def save(self, *args, **kwargs):
        """
        Checking if the image has been changed. If changed, apply compression and converse to webp
        """
        if self._old_img != self.img:
            self.img = compress(self.img)
        super().save(*args, **kwargs)

checkout/forms.py
from django import forms
from django_countries.widgets import CountrySelectWidget

from .models import Address


class CheckoutForm(forms.ModelForm):
    """Checkout form with attrs for Material Design"""

    class Meta:
        model = Address
        fields = "__all__"
        widgets = {
            "email": forms.EmailInput(attrs={"class": "form-control"}),
            "shipping_name": forms.TextInput(attrs={"class": "form-control"}),
            "shipping_street_address": forms.TextInput(attrs={"class": "form-control"}),
            "shipping_apartment_address": forms.TextInput(
                attrs={"class": "form-control"}
            ),
            "shipping_city": forms.TextInput(attrs={"class": "form-control"}),
            "shipping_country": CountrySelectWidget(
                attrs={"class": "browser-default custom-select d-block w-100"}
            ),
            "shipping_zip": forms.NumberInput(attrs={"class": "form-control"}),
            "billing_name": forms.TextInput(attrs={"class": "form-control"}),
            "billing_street_address": forms.TextInput(attrs={"class": "form-control"}),
            "billing_apartment_address": forms.TextInput(
                attrs={"class": "form-control"}
            ),
            "billing_city": forms.TextInput(attrs={"class": "form-control"}),
            "billing_country": CountrySelectWidget(
                attrs={"class": "browser-default custom-select d-block w-100"}
            ),
            "billing_zip": forms.NumberInput(attrs={"class": "form-control"}),
        }

payment/forms.py
from django import forms


class PaymentForm(forms.Form):
    stripeToken = forms.CharField(required=False)
    save = forms.BooleanField(required=False)
    use_default = forms.BooleanField(required=False)

checkout/views.py
from decouple import config
from django.shortcuts import redirect
from django.contrib import messages
from django.urls import reverse_lazy
from django.views.generic import edit
from django.utils.translation import gettext_lazy as _

from order.models import Order
from .models import Address
from .forms import CheckoutForm


class CheckoutView(edit.FormView):
    template_name = "checkout.html"
    form_class = CheckoutForm
    success_url = reverse_lazy("payment:payment")

    def get_form(self, *args, **kwargs):
        """If user is not authenticated, exclude field "Default" from form"""
        form = super().get_form(self.form_class)
        if not self.request.user.is_authenticated:
            form.fields.pop("default")
        return form

    def form_valid(self, form):
        """If form is valid, save form and model, add address to order"""
        action = form.save(commit=False)
        if self.request.user.is_authenticated:
            action.user = self.request.user
        action.save()
        order = (
            Order.objects.filter(
                ordered=False,
                user=(
                    self.request.user if self.request.user.is_authenticated else None
                ),
                session_key=(
                    None
                    if self.request.user.is_authenticated
                    else self.request.session.session_key
                ),
            )
            .select_related("address")
            .first()
        )
        order.address = action
        order.save()
        return super().form_valid(form)

    def get_initial(self):
        """
        If user is authenticated and has saved
        address previously, get this address as initials for form
        """
        initial = super().get_initial()
        if self.request.user.is_authenticated:
            default_address = Address.objects.filter(
                user=self.request.user, default=True
            ).first()
            if default_address is not None:
                initial.update(
                    {
                        "email": default_address.email,
                        "shipping_name": default_address.shipping_name,
                        "shipping_street_address": default_address.shipping_street_address,
                        "shipping_apartment_address": default_address.shipping_apartment_address,
                        "shipping_city": default_address.shipping_city,
                        "shipping_country": default_address.shipping_country,
                        "shipping_zip": default_address.shipping_zip,
                        "billing_name": default_address.billing_name,
                        "billing_street_address": default_address.billing_street_address,
                        "billing_apartment_address": default_address.billing_apartment_address,
                        "billing_city": default_address.billing_city,
                        "billing_country": default_address.billing_country,
                        "billing_zip": default_address.billing_zip,
                    }
                )
        return initial

    def get_context_data(self, **kwargs):
        """
        Getting context: paypal id, order and items
        """
        context = super().get_context_data(**kwargs)
        context.update(
            {
                "client_id": config("PAYPAL_CLIENT_ID"),
                "currency": "EUR",
            }
        )
        try:
            order = (
                Order.objects.filter(
                    ordered=False,
                    user=(
                        self.request.user
                        if self.request.user.is_authenticated
                        else None
                    ),
                    session_key=(
                        None
                        if self.request.user.is_authenticated
                        else self.request.session.session_key
                    ),
                )
                .select_related("address")
                .prefetch_related("orderitem_set")
                .first()
            )
            order_items = order.orderitem_set.all()
            if order is not None:
                context["order"] = order
                context["order_items"] = order_items
                if order.address:
                    context["order_has_address"] = True
        except AttributeError:
            messages.info(self.request, _("You do not have anything in cart"))
            return redirect("core:home")
        return context

templates/checkout.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% load i18n %}
{% block head_title %}
  Checkout
{% endblock head_title %}
{% block content %}
  <main>
    <div class="container wow fadeIn">
      <h2 class="my-5 h2 text-center">{% trans "Checkout Form" %}</h2>
      <div class="row">
        <div class="col-md-8 mb-1">
          <div class="card">
            <form method="post" class="card-body">
              {% csrf_token %}
              <div class="md-form">
                {{ form.errors }}
                {{ form.non_field_errors }}
              </div>
              <div class="md-form">
                {{ form.email.errors }}
                {{ form.email }}
                {{ form.email.label_tag }}
                <small class="form-text text-muted">{% trans "Your email will only be used for notification about your order" %}</small>
              </div>
              <h3 class="my-5 h3 text-center">{% trans "Shipping address" %}</h3>
              <div class="md-form">
                {{ form.shipping_name.errors }}
                {{ form.shipping_name }}
                <label for="id_shipping_name">{% trans "Full name" %}*</label>
              </div>
              <div class="md-form">
                {{ form.shipping_street_address.errors }}
                {{ form.shipping_street_address }}
                <label for="id_shipping_street_address">{% trans "Street, house number" %}*</label>
              </div>
              <div class="md-form">
                {{ form.shipping_apartment_address.errors }}
                {{ form.shipping_apartment_address }}
                <label for="id_shipping_apartment_address">{% trans "Apartment/company" %}</label>
              </div>
              <div class="row">
                <div class="col-lg-4 col-md-6 mb-4">
                  <div class="md-form">
                    {{ form.shipping_zip.errors }}
                    {{ form.shipping_zip }}
                    <label for="id_shipping_zip">{% trans "Zip code" %}*</label>
                  </div>
                </div>
                <div class="col-lg-4 col-md-6 mb-4">
                  <div class="md-form">
                    {{ form.shipping_city.errors }}
                    {{ form.shipping_city }}
                    <label for="id_shipping_city">{% trans "City" %}*</label>
                  </div>
                </div>
                <div class="col-lg-4 col-md-6 mb-4">
                  <div class="md-form">
                    {{ form.shipping_country.errors }}
                    {{ form.shipping_country }}
                    <small class="form-text text-muted">{% trans "We currently work only inside EU" %}</small>
                  </div>
                </div>
              </div>
              <button class="btn btn-secondary btn-lg btn-block"
                      name="Copy"
                      type="button"
                      onclick="copyShipping()">
                <i class="far fa-clone"></i>
                {% trans "Copy from shipping to billing" %}
              </button>
              <h3 class="my-5 h3 text-center">{% trans "Billing address" %}</h3>
              <div class="md-form">
                {{ form.billing_name.errors }}
                {{ form.billing_name }}
                <label id="id_billing_name_label" for="id_billing_name">{% trans "Full name" %}*</label>
              </div>
              <div class="md-form">
                {{ form.billing_street_address.errors }}
                {{ form.billing_street_address }}
                <label id="id_billing_street_address_label" for="id_billing_street_address">{% trans "Street, house number" %}*</label>
              </div>
              <div class="md-form">
                {{ form.billing_apartment_address.errors }}
                {{ form.billing_apartment_address }}
                <label id="id_billing_apartment_address_label"
                       for="id_billing_apartment_address">
                  {% trans "Apartment/company" %}*
                </label>
              </div>
              <div class="row">
                <div class="col-lg-4 col-md-6 mb-4">
                  <div class="md-form">
                    {{ form.billing_zip.errors }}
                    {{ form.billing_zip }}
                    <label id="id_billing_zip_label" for="id_billing_zip">{% trans "Zip code" %}*</label>
                  </div>
                </div>
                <div class="col-lg-4 col-md-6 mb-4">
                  <div class="md-form">
                    {{ form.billing_city.errors }}
                    {{ form.billing_city }}
                    <label id="id_billing_city_label" for="id_billing_city">{% trans "City" %}*</label>
                  </div>
                </div>
                <div class="col-lg-4 col-md-6 mb-4">
                  <div class="md-form">
                    {{ form.billing_country.errors }}
                    {{ form.billing_country }}
                    <small class="form-text text-muted">{% trans "We currently work only inside EU" %}</small>
                  </div>
                </div>
              </div>
              {% if request.user.is_authenticated %}
                <div class="custom-control custom-checkbox mb-3">
                  {{ form.default.errors }}
                  {{ form.default }}
                  <label for="id_default">{% trans "Save for future use" %}</label>
                </div>
              {% endif %}
              <button class="btn btn-primary btn-lg btn-block" name="Submit" type="submit">
                <i class="fas fa-angle-double-right"></i> {% trans "Continue to payment" %}
              </button>
            </form>
          </div>
        </div>
        <div class="col-md-4 mb-1">{% include "order_snippet.html" %}</div>
      </div>
    </div>
    <!-- Modal -->
    <div class="modal fade"
         id="addressModal"
         tabindex="-1"
         role="dialog"
         aria-labelledby="exampleModalCenterTitle"
         aria-hidden="true">
      <!-- Add .modal-dialog-centered to .modal-dialog to vertically center the modal -->
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">{% trans "Order address" %}</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-body">
            <p>
              You have already indicated your address previously:
              <table class="table table-hover table-sm">
                <thead class="blue-text">
                  <tr>
                    <th scope="col">{% trans "Shipping address" %}</th>
                    <th scope="col">{% trans "Billing address" %}</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>{{ order.address.shipping_name }}</td>
                    <td>{{ order.address.billing_name }}</td>
                  </tr>
                  <tr>
                    <td>{{ order.address.shipping_street_address }}</td>
                    <td>{{ order.address.billing_street_address }}</td>
                  </tr>
                  <tr>
                    <td>
                      {{ order.address.shipping_apartment_address }}
                    </td>
                    <td>
                      {{ order.address.billing_apartment_address }}
                    </td>
                  </tr>
                  <tr>
                    <td>
                      {{ order.address.shipping_city }}
                    </td>
                    <td>
                      {{ order.address.billing_city }}
                    </td>
                  </tr>
                  <tr>
                    <td>
                      {{ order.address.shipping_country }}
                    </td>
                    <td>
                      {{ order.address.billing_country }}
                    </td>
                  </tr>
                  <tr>
                    <td>
                      {{ order.address.shipping_zip }}
                    </td>
                    <td>
                      {{ order.address.billing_zip }}
                    </td>
                  </tr>
                </tbody>
              </table>
              {% trans "Do you wish to use it for this order?" %}
            </p>
          </div>
          <div class="modal-footer">
            <a href="{% url "payment:payment" %}">
              <button type="button" class="btn btn-primary">
                {% trans "Yes, continue to payment" %}
              </button>
            </a>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">
              {% trans "No, I will give another address" %}
            </button>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock content %}
{% block extra_body %}
  <script>
    function copyShipping() {
      var shipping_name = document.getElementById("id_shipping_name"),
          shipping_street_address = document.getElementById("id_shipping_street_address"),
          shipping_apartment_address = document.getElementById("id_shipping_apartment_address"),
          shipping_zip = document.getElementById("id_shipping_zip"),
          shipping_city = document.getElementById("id_shipping_city"),
          shipping_country = document.getElementById("id_shipping_country"),
          billing_name = document.getElementById("id_billing_name");
          billing_name_label = document.getElementById("id_billing_name_label"),
          billing_street_address = document.getElementById("id_billing_street_address"),
          billing_street_address_label = document.getElementById("id_billing_street_address_label"),
          billing_apartment_address = document.getElementById("id_billing_apartment_address"),
          billing_apartment_address_label = document.getElementById("id_billing_apartment_address_label"),
          billing_zip = document.getElementById("id_billing_zip"),
          billing_zip_label = document.getElementById("id_billing_zip_label"),
          billing_city = document.getElementById("id_billing_city"),
          billing_city_label = document.getElementById("id_billing_city_label"),
          billing_country = document.getElementById("id_billing_country"),
      billing_name.value = shipping_name.value;
      billing_name_label.className += " active";
      billing_street_address.value = shipping_street_address.value;
      billing_street_address_label.className += " active";
      billing_apartment_address.value = shipping_apartment_address.value;
      billing_apartment_address_label.className += " active";
      billing_zip.value = shipping_zip.value;
      billing_zip_label.className += " active";
      billing_city.value = shipping_city.value;
      billing_city_label.className += " active";
      billing_country.value = shipping_country.value;
      };
  </script>
  <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
  {{ order_has_address|json_script:"address" }}
  <script>
  $( document ).ready(function() {
    var address = JSON.parse(document.getElementById("address").textContent);
    if (address) {
      $("#addressModal").modal("show");
    }
  });
  </script>
  <script src="https://www.paypal.com/sdk/js?client-id={{ client_id }}&currency={{ currency }}" async></script>
{% endblock extra_body %}

templates/impressum.html
{% extends "base.html" %}
{% load i18n %}
{% block head_title %}
  {% trans "Impressum" %}
{% endblock head_title %}
{% block content %}
  <main>
    <div class="container">
      <h2 class="my-5 h2 text-center">{% trans "Impressum" %}</h2>
      <div class="card">
        <div class="card-body">
          {% blocktranslate %}
        <p>Anbieter:
          <br />
          Max Mustermann
          <br />
          Musterstraße 1
          <br />
          80999 München
        </p>
        <p>Kontakt:
          <br />
          Telefon: 089/1234567-8
          <br />
          Telefax: 089/1234567-9
          <br />
          E-Mail: mail@mustermann.de
          <br />Website: www.mustermann.de
        </p>
        <p></p>
        <p>Bei redaktionellen Inhalten:</p>
        <p>Verantwortlich nach § 55 Abs.2 RStV
          <br />
          Moritz Schreiberling
          <br />
          Musterstraße 2
          <br />
          80999 München
        </p>
      {% endblocktranslate %}
        </div>
      </div>
    </div>
  </main>
{% endblock content %}

templates/request_refund.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}
{% block head_title %}
  {% translate "Request Refund" %}
{% endblock head_title %}
{% block content %}
  <main>
    <div class="container">
      <h2 class="my-5 h2 text-center">{% translate "Request Refund" %}</h2>
      <form method="post" class="card-body">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">{% translate "Submit" %}</button>
      </form>
    </div>
  </main>
{% endblock content %}